const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Rotate,
		C3.Behaviors.NoSave,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.PickAll,
		C3.JavaScriptInEvents.Folhainicio_Event2_Act2
	];
};
self.C3_JsPropNameTable = [
	{Âncora: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sólido: 0},
	{chao1: 0},
	{chao2: 0},
	{chao3: 0},
	{chao4: 0},
	{chao5: 0},
	{chao6: 0},
	{chao7: 0},
	{chao8: 0},
	{chao9: 0},
	{chao10: 0},
	{chao11: 0},
	{grama1: 0},
	{chao12: 0},
	{chao13: 0},
	{chao14: 0},
	{chao15: 0},
	{chao16: 0},
	{chao17: 0},
	{chao18: 0},
	{chao19: 0},
	{chao20: 0},
	{chao21: 0},
	{chao22: 0},
	{grama2: 0},
	{chao23: 0},
	{chao24: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{personagem: 0},
	{Teclado: 0},
	{chao25: 0},
	{chao26: 0},
	{chao27: 0},
	{chao28: 0},
	{chao29: 0},
	{chao30: 0},
	{chao31: 0},
	{chao32: 0},
	{chao33: 0},
	{chao34: 0},
	{chao35: 0},
	{chao36: 0},
	{chao37: 0},
	{chao38: 0},
	{ceu1: 0},
	{ceu2: 0},
	{ceu3: 0},
	{ceu4: 0},
	{ceu5: 0},
	{ceu6: 0},
	{ceu7: 0},
	{ceu8: 0},
	{chaoCima1: 0},
	{chaoCima2: 0},
	{chaoCima3: 0},
	{chaoCima4: 0},
	{chaoCima5: 0},
	{chaoCima6: 0},
	{botoes: 0},
	{Sprite2: 0},
	{bordaPorta1: 0},
	{bordaPorta2: 0},
	{bordaPorta3: 0},
	{bordaPorta4: 0},
	{bordaPorta5: 0},
	{bordaPorta6: 0},
	{bordaPorta7: 0},
	{bordaPorta8: 0},
	{porta: 0},
	{gelo1: 0},
	{gelo2: 0},
	{gelo3: 0},
	{gelo4: 0},
	{gelo5: 0},
	{gelo6: 0},
	{gelo7: 0},
	{gelo8: 0},
	{gelo10: 0},
	{gelo11: 0},
	{gelo12: 0},
	{gelo13: 0},
	{gelo14: 0},
	{gelo15: 0},
	{gelo17: 0},
	{gelo18: 0},
	{gelo19: 0},
	{gelo20: 0},
	{gelo21: 0},
	{gelo22: 0},
	{gelo23: 0},
	{gelo24: 0},
	{gelo25: 0},
	{gelo26: 0},
	{gelo27: 0},
	{gelo28: 0},
	{gelo30: 0},
	{gelo31: 0},
	{gelo32: 0},
	{gelo33: 0},
	{gelo34: 0},
	{gelo37: 0},
	{gelo38: 0},
	{gelo39: 0},
	{gelo40: 0},
	{neve1: 0},
	{grama3: 0},
	{grama4: 0},
	{grama5: 0},
	{grama6: 0},
	{grama7: 0},
	{grama8: 0},
	{grama9: 0},
	{grama10: 0},
	{grama11: 0},
	{grama12: 0},
	{grama13: 0},
	{grama14: 0},
	{grama15: 0},
	{grama16: 0},
	{grama17: 0},
	{grama18: 0},
	{grama19: 0},
	{grama20: 0},
	{grama21: 0},
	{neve2: 0},
	{neve3: 0},
	{neve4: 0},
	{neve5: 0},
	{neve6: 0},
	{neve7: 0},
	{neve8: 0},
	{neve10: 0},
	{neve11: 0},
	{neve12: 0},
	{neve13: 0},
	{neve14: 0},
	{neve15: 0},
	{neve17: 0},
	{neve18: 0},
	{neve19: 0},
	{neve20: 0},
	{chaoCima7: 0},
	{chaoCima8: 0},
	{chaoCima9: 0},
	{grama22: 0},
	{grama23: 0},
	{grama24: 0},
	{Mouse: 0},
	{botaoJogar: 0},
	{Girar: 0},
	{moeda: 0},
	{moeda2: 0},
	{sensor: 0},
	{muro1: 0},
	{geloMoeda: 0},
	{terra: 0},
	{terra2: 0},
	{terra3: 0},
	{terra4: 0},
	{terra5: 0},
	{terra6: 0},
	{terra7: 0},
	{terra9: 0},
	{terra10: 0},
	{terra11: 0},
	{terra12: 0},
	{terra13: 0},
	{terra14: 0},
	{terra15: 0},
	{NãoSalvar: 0},
	{terra16: 0},
	{terra17: 0},
	{terra18: 0},
	{terra19: 0},
	{terra20: 0},
	{terra21: 0},
	{terra22: 0},
	{terra23: 0},
	{terra24: 0},
	{terra25: 0},
	{terra26: 0},
	{terra27: 0},
	{terra28: 0},
	{terra29: 0},
	{terra30: 0},
	{terra32: 0},
	{terra33: 0},
	{terra34: 0},
	{terra35: 0},
	{terra36: 0},
	{terra37: 0},
	{terra38: 0},
	{terra39: 0},
	{terra40: 0},
	{terra41: 0},
	{terra42: 0},
	{terra43: 0},
	{terra44: 0},
	{terra45: 0},
	{terra46: 0},
	{ponte: 0},
	{espinho2: 0},
	{soloMoeda: 0},
	{muro2: 0},
	{muro3: 0},
	{moeda3: 0},
	{sensorBuraco: 0},
	{chao: 0},
	{voltar: 0},
	{instrucoes: 0},
	{Sprite: 0},
	{NomeInstrucoes: 0},
	{pular: 0},
	{andaEsquerda: 0},
	{andaDireita: 0},
	{flocos: 0},
	{jogarAgora2: 0},
	{jogarAgora: 0},
	{moeda4: 0},
	{Áudio: 0},
	{moeda5: 0},
	{sensor2: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	chao1: class extends self.ISpriteInstance {},
	chao2: class extends self.ISpriteInstance {},
	chao3: class extends self.ISpriteInstance {},
	chao4: class extends self.ISpriteInstance {},
	chao5: class extends self.ISpriteInstance {},
	chao6: class extends self.ISpriteInstance {},
	chao7: class extends self.ISpriteInstance {},
	chao8: class extends self.ISpriteInstance {},
	chao9: class extends self.ISpriteInstance {},
	chao10: class extends self.ISpriteInstance {},
	chao11: class extends self.ISpriteInstance {},
	grama1: class extends self.ISpriteInstance {},
	chao12: class extends self.ISpriteInstance {},
	chao13: class extends self.ISpriteInstance {},
	chao14: class extends self.ISpriteInstance {},
	chao15: class extends self.ISpriteInstance {},
	chao16: class extends self.ISpriteInstance {},
	chao17: class extends self.ISpriteInstance {},
	chao18: class extends self.ISpriteInstance {},
	chao19: class extends self.ISpriteInstance {},
	chao20: class extends self.ISpriteInstance {},
	chao21: class extends self.ISpriteInstance {},
	chao22: class extends self.ISpriteInstance {},
	grama2: class extends self.ISpriteInstance {},
	chao23: class extends self.ISpriteInstance {},
	chao24: class extends self.ISpriteInstance {},
	personagem: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	chao25: class extends self.ISpriteInstance {},
	chao26: class extends self.ISpriteInstance {},
	chao27: class extends self.ISpriteInstance {},
	chao28: class extends self.ISpriteInstance {},
	chao29: class extends self.ISpriteInstance {},
	chao30: class extends self.ISpriteInstance {},
	chao31: class extends self.ISpriteInstance {},
	chao32: class extends self.ISpriteInstance {},
	chao33: class extends self.ISpriteInstance {},
	chao34: class extends self.ISpriteInstance {},
	chao35: class extends self.ISpriteInstance {},
	chao36: class extends self.ISpriteInstance {},
	chao37: class extends self.ISpriteInstance {},
	chao38: class extends self.ISpriteInstance {},
	ceu1: class extends self.ISpriteInstance {},
	ceu2: class extends self.ISpriteInstance {},
	ceu3: class extends self.ISpriteInstance {},
	ceu4: class extends self.ISpriteInstance {},
	ceu5: class extends self.ISpriteInstance {},
	ceu6: class extends self.ISpriteInstance {},
	ceu7: class extends self.ISpriteInstance {},
	ceu8: class extends self.ISpriteInstance {},
	chaoCima1: class extends self.ISpriteInstance {},
	chaoCima2: class extends self.ISpriteInstance {},
	chaoCima3: class extends self.ISpriteInstance {},
	chaoCima4: class extends self.ISpriteInstance {},
	chaoCima5: class extends self.ISpriteInstance {},
	chaoCima6: class extends self.ISpriteInstance {},
	botoes: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	bordaPorta1: class extends self.ISpriteInstance {},
	bordaPorta2: class extends self.ISpriteInstance {},
	bordaPorta3: class extends self.ISpriteInstance {},
	bordaPorta4: class extends self.ISpriteInstance {},
	bordaPorta5: class extends self.ISpriteInstance {},
	bordaPorta6: class extends self.ISpriteInstance {},
	bordaPorta7: class extends self.ISpriteInstance {},
	bordaPorta8: class extends self.ISpriteInstance {},
	porta: class extends self.ISpriteInstance {},
	gelo1: class extends self.ISpriteInstance {},
	gelo2: class extends self.ISpriteInstance {},
	gelo3: class extends self.ISpriteInstance {},
	gelo4: class extends self.ISpriteInstance {},
	gelo5: class extends self.ISpriteInstance {},
	gelo6: class extends self.ISpriteInstance {},
	gelo7: class extends self.ISpriteInstance {},
	gelo8: class extends self.ISpriteInstance {},
	gelo10: class extends self.ISpriteInstance {},
	gelo11: class extends self.ISpriteInstance {},
	gelo12: class extends self.ISpriteInstance {},
	gelo13: class extends self.ISpriteInstance {},
	gelo14: class extends self.ISpriteInstance {},
	gelo15: class extends self.ISpriteInstance {},
	gelo17: class extends self.ISpriteInstance {},
	gelo18: class extends self.ISpriteInstance {},
	gelo19: class extends self.ISpriteInstance {},
	gelo20: class extends self.ISpriteInstance {},
	gelo21: class extends self.ISpriteInstance {},
	gelo22: class extends self.ISpriteInstance {},
	gelo23: class extends self.ISpriteInstance {},
	gelo24: class extends self.ISpriteInstance {},
	gelo25: class extends self.ISpriteInstance {},
	gelo26: class extends self.ISpriteInstance {},
	gelo27: class extends self.ISpriteInstance {},
	gelo28: class extends self.ISpriteInstance {},
	gelo30: class extends self.ISpriteInstance {},
	gelo31: class extends self.ISpriteInstance {},
	gelo32: class extends self.ISpriteInstance {},
	gelo33: class extends self.ISpriteInstance {},
	gelo34: class extends self.ISpriteInstance {},
	gelo37: class extends self.ISpriteInstance {},
	gelo38: class extends self.ISpriteInstance {},
	gelo39: class extends self.ISpriteInstance {},
	gelo40: class extends self.ISpriteInstance {},
	neve1: class extends self.ISpriteInstance {},
	grama3: class extends self.ISpriteInstance {},
	grama4: class extends self.ISpriteInstance {},
	grama5: class extends self.ISpriteInstance {},
	grama6: class extends self.ISpriteInstance {},
	grama7: class extends self.ISpriteInstance {},
	grama8: class extends self.ISpriteInstance {},
	grama9: class extends self.ISpriteInstance {},
	grama10: class extends self.ISpriteInstance {},
	grama11: class extends self.ISpriteInstance {},
	grama12: class extends self.ISpriteInstance {},
	grama13: class extends self.ISpriteInstance {},
	grama14: class extends self.ISpriteInstance {},
	grama15: class extends self.ISpriteInstance {},
	grama16: class extends self.ISpriteInstance {},
	grama17: class extends self.ISpriteInstance {},
	grama18: class extends self.ISpriteInstance {},
	grama19: class extends self.ISpriteInstance {},
	grama20: class extends self.ISpriteInstance {},
	grama21: class extends self.ISpriteInstance {},
	neve2: class extends self.ISpriteInstance {},
	neve3: class extends self.ISpriteInstance {},
	neve4: class extends self.ISpriteInstance {},
	neve5: class extends self.ISpriteInstance {},
	neve6: class extends self.ISpriteInstance {},
	neve7: class extends self.ISpriteInstance {},
	neve8: class extends self.ISpriteInstance {},
	neve10: class extends self.ISpriteInstance {},
	neve11: class extends self.ISpriteInstance {},
	neve12: class extends self.ISpriteInstance {},
	neve13: class extends self.ISpriteInstance {},
	neve14: class extends self.ISpriteInstance {},
	neve15: class extends self.ISpriteInstance {},
	neve17: class extends self.ISpriteInstance {},
	neve18: class extends self.ISpriteInstance {},
	neve19: class extends self.ISpriteInstance {},
	neve20: class extends self.ISpriteInstance {},
	chaoCima7: class extends self.ISpriteInstance {},
	chaoCima8: class extends self.ISpriteInstance {},
	chaoCima9: class extends self.ISpriteInstance {},
	grama22: class extends self.ISpriteInstance {},
	grama23: class extends self.ISpriteInstance {},
	grama24: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	botaoJogar: class extends self.ISpriteFontInstance {},
	moeda: class extends self.ISpriteInstance {},
	moeda2: class extends self.ISpriteInstance {},
	sensor: class extends self.ISpriteInstance {},
	muro1: class extends self.ISpriteInstance {},
	geloMoeda: class extends self.ISpriteInstance {},
	terra: class extends self.ISpriteInstance {},
	terra2: class extends self.ISpriteInstance {},
	terra3: class extends self.ISpriteInstance {},
	terra4: class extends self.ISpriteInstance {},
	terra5: class extends self.ISpriteInstance {},
	terra6: class extends self.ISpriteInstance {},
	terra7: class extends self.ISpriteInstance {},
	terra9: class extends self.ISpriteInstance {},
	terra10: class extends self.ISpriteInstance {},
	terra11: class extends self.ISpriteInstance {},
	terra12: class extends self.ISpriteInstance {},
	terra13: class extends self.ISpriteInstance {},
	terra14: class extends self.ISpriteInstance {},
	terra15: class extends self.ISpriteInstance {},
	terra16: class extends self.ISpriteInstance {},
	terra17: class extends self.ISpriteInstance {},
	terra18: class extends self.ISpriteInstance {},
	terra19: class extends self.ISpriteInstance {},
	terra20: class extends self.ISpriteInstance {},
	terra21: class extends self.ISpriteInstance {},
	terra22: class extends self.ISpriteInstance {},
	terra23: class extends self.ISpriteInstance {},
	terra24: class extends self.ISpriteInstance {},
	terra25: class extends self.ISpriteInstance {},
	terra26: class extends self.ISpriteInstance {},
	terra27: class extends self.ISpriteInstance {},
	terra28: class extends self.ISpriteInstance {},
	terra29: class extends self.ISpriteInstance {},
	terra30: class extends self.ISpriteInstance {},
	terra32: class extends self.ISpriteInstance {},
	terra33: class extends self.ISpriteInstance {},
	terra34: class extends self.ISpriteInstance {},
	terra35: class extends self.ISpriteInstance {},
	terra36: class extends self.ISpriteInstance {},
	terra37: class extends self.ISpriteInstance {},
	terra38: class extends self.ISpriteInstance {},
	terra39: class extends self.ISpriteInstance {},
	terra40: class extends self.ISpriteInstance {},
	terra41: class extends self.ISpriteInstance {},
	terra42: class extends self.ISpriteInstance {},
	terra43: class extends self.ISpriteInstance {},
	terra44: class extends self.ISpriteInstance {},
	terra45: class extends self.ISpriteInstance {},
	terra46: class extends self.ISpriteInstance {},
	ponte: class extends self.ISpriteInstance {},
	espinho2: class extends self.ISpriteInstance {},
	soloMoeda: class extends self.ISpriteInstance {},
	muro2: class extends self.ISpriteInstance {},
	muro3: class extends self.ISpriteInstance {},
	moeda3: class extends self.ISpriteInstance {},
	sensorBuraco: class extends self.ISpriteInstance {},
	chao: class extends self.ISpriteInstance {},
	voltar: class extends self.ISpriteInstance {},
	instrucoes: class extends self.ISpriteFontInstance {},
	Sprite: class extends self.ISpriteInstance {},
	NomeInstrucoes: class extends self.ISpriteFontInstance {},
	pular: class extends self.ISpriteFontInstance {},
	andaEsquerda: class extends self.ISpriteFontInstance {},
	andaDireita: class extends self.ISpriteFontInstance {},
	flocos: class extends self.ISpriteInstance {},
	jogarAgora2: class extends self.ISpriteInstance {},
	jogarAgora: class extends self.ISpriteFontInstance {},
	moeda4: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	moeda5: class extends self.ISpriteInstance {},
	sensor2: class extends self.ISpriteInstance {}
}